Rakefile

```gem build mini_portile.gemspec``` works, but most users probably expect a rake task for this.

Add gem tasks that were removed in commit a49fc5ec3.

---

lib/mini_portile2/mini_portile.rb

Invoke configure directly on Unix-systems, not by passing it to `sh`.

---

lib/mini_portile2/mini_portile.rb
test/assets/git/config
test/assets/patch 1.diff
test/test_cook.rb

Avoid e.g. expanding tabs to spaces (which e.g. can break shell scripts
and makefiles) when the user's git config fixes whitespaces by default.

ignore git ws config when patching

---

.travis.yml
lib/mini_portile2.rb
lib/mini_portile2/mini_portile.rb
lib/mini_portile2/mini_portile_cmake.rb
test/assets/test-cmake-1.0/CMakeLists.txt
test/assets/test-cmake-1.0/hello.c
test/helper.rb
test/test_cmake.rb
test/test_cook.rb
test/test_digest.rb

CMake-based projects are similar to autoconf-based projects, except for the `configure` step.
This PR adds experimental support for CMake-based projects.
@larskanis would love to hear your thoughts.

add cmake support

---

CHANGELOG.md
lib/mini_portile2/mini_portile.rb
lib/mini_portile2/mini_portile_cmake.rb

MD5 is no longer available in environments with strict security settings
especially when running in FIPS mode.
Fixes #78

Remove MD5 for configure options hashing - it's unnecessary.

---

lib/mini_portile2/mini_portile.rb

Raise a suitable error message, if tar can't be found

---

lib/mini_portile2/mini_portile.rb

Skip progress report when Content-Length is unavailable

---

lib/mini_portile2/mini_portile.rb

In case multiple GPG public keys are given, the current implementation only removes the first key after use and leaves the others, which will be used to verify subsequent downloads (insecure). This patch makes sure to remove all of them.

Remove all the imported pubkeys from keyring

---

mini_portile2.gemspec

This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/mini_portile or some tools or APIs that use the gem's metadata.

GitHub is HTTPS by default

---

CHANGELOG.md
lib/mini_portile2/mini_portile.rb
test/test_execute.rb

feat: #execute now accepts an optional :env hash

---

.github/workflows/ci.yml

these were removed in 87fd0b0 but are still supported according to the
gemspec.

ci: add 2.3 and 2.4 to the matrix

---

CHANGELOG.md
README.md
examples/Rakefile
lib/mini_portile2/mini_portile.rb
test/test_cook.rb

`Recipe#source_directory` allows recipes to build against a local source directory instead of pulling down remote tarballs.

add source directory support

---

CHANGELOG.md
Gemfile
lib/mini_portile2/mini_portile.rb
mini_portile2.gemspec
test/test_download.rb

v2.5.2 added `net-ftp` as a gem dependency to try to anticipate Ruby 3.1 changes.
However, for users of Ruby 2.7 and earlier, this resulted in warnings as demonstrated at #105.
This change makes `net-ftp` an optional (or "soft") dependency, so that if it's loaded the FTP functionality works; but if it's not loaded then an exception is raised informing the user what's wrong.

address net-ftp warnings

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
lib/mini_portile2/mini_portile.rb
lib/mini_portile2/mini_portile_cmake.rb
test/helper.rb
test/test_cmake.rb
test/test_cook.rb

For CentOS, RHEL, and Amazon Linux 2 use case, we sometimes need to use `cmake3` command instead of `cmake` command.
Could you provide how to specify arbitrary cmake command at `#initialize` on `MiniPortileCMake` class?
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

cmake: Support cmake command replacement on #initialize

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
lib/mini_portile2/mini_portile.rb
mini_portile2.gemspec

This PR started as a change adding Darwin builds to CI.
However, I noticed that Windows 3.1 and head builds were really slow, and looking at the logs I can see that it's because it takes 2 minutes to timeout on failed downloads. So I added a feature whereby timeouts can be specifed, and default to 10 seconds.

ci: add darwin coverage to the ci matrix, specify timeouts on windows

---

CHANGELOG.md
examples/Rakefile
lib/mini_portile2/mini_portile.rb

The latest libxml2 release is only available as an xz-compressed archive, so let's add support.

feat: support xz-compressed archives

---

mini_portile2.gemspec

because windows 3.0 ships with bundler 2.2 and is failing in CI

dep(dev): loosen bundler dependency

---

CHANGELOG.md
lib/mini_portile2/mini_portile.rb

Fixes #119
cc @h0tw1r3 who has a co-author credit on this one
Note that #121 introduced some tests that exercise patching.

fix: handle patching in dirs that resemble an actual git dir

---

lib/mini_portile2/mini_portile.rb

This PR updates the `source_directory` behavior to use a posix path internally, because autoconf `configure` scripts get confused when presented with a windows path.
So if the windows path to the source directory is `D:\temp\project`, the configure script will be invoked as `/D/temp/project/configure` so that detection of aux files will properly look in the script's directory.
Also, this PR updates the behavior on failure to output the _complete_ log (not just the last 20 lines), and additionally will output the entire contents of `config.log` from the configure step.

fix: source_directory option on windows

---

lib/mini_portile2/mini_portile.rb
lib/mini_portile2/mini_portile_cmake.rb
test/test_cmake.rb

For the standard `make`, mini_portile provides the `configure` script with the `--host` parameter, and the script figures out the target compilers to use. With CMake, we don't have that benefit so we need to set the C and C++ compilers ourselves.
This commit uses a simple heuristic to find the target compilers:
1. For macOS, use `clang` and `clang++`. Otherwise use `gcc` and `gcc++`.
2. We search the PATH for `<host>-compiler`. Use that if we find it. Otherwise default to the base compilers.
To make CMake work with cross-compilation, a number of variables have to be set:
- CMAKE_SYSTEM_PROCESSOR
- CMAKE_SYSTEM_NAME
- CMAKE_C_COMPILER
- CMAKE_CXX_COMPILER
Closes #128

[cmake] Automatically add required cross-compilation variables

---

lib/mini_portile2/mini_portile.rb

Older rubies complain about `@gcc_command` from `detect_host`. Fix by rearranging the order of variable initialization.

fix: avoid uninitialized ivar warnings

---

.github/workflows/ci.yml
.gitignore
examples/Rakefile
lib/mini_portile2/mini_portile.rb
test/assets/pkgconf/libxml2/libxml-2.0.pc
test/assets/pkgconf/libxslt/libexslt.pc
test/assets/pkgconf/libxslt/libxslt.pc
test/test_activate.rb
test/test_mkmf_config.rb

Closes #118 
Currently, each C extension is responsible for figuring out the compiler and linker flags; and even using pkg-config is fraught because of lack of features or bugs in older Rubies and OS platforms.
The approach taken here is for a new method, `MiniPortile#mkmf_config`, to support reading a pkg-config file and set `$LDFLAGS` and `$CFLAGS` appropriately, doing all the hacky things that require specialized knowledge but that I don't want gem authors to have to learn how to do.
This should mean we don't need to use the pkgconf trick in extconf.rb anymore, which completely avoids the behavior of Fedora's pkgconf described in #118.

feat: `MiniPortile#mkmf_config` which supports pkg-config files to configure compiler and linker flags

---

examples/Rakefile
lib/mini_portile2/mini_portile.rb
test/assets/pkgconf/libxml2/libxml-2.0.pc
test/assets/pkgconf/libxslt/libxslt.pc
test/test_mkmf_config.rb

- prepend package search directories to $INCFLAGS and $LIBPATH
- append compiler and linker flags to $CFLAGS and $libs
Note that we use $LIBPATH instead of $LDFLAGS so that shared libraries will be found again thanks to the `-Wl,-rpath` linker flag that is added by MakeMakefile

feat: more precise implementation of mkmf_config

---

examples/Rakefile
lib/mini_portile2/mini_portile.rb
test/test_mkmf_config.rb
test/test_recipe.rb

v2.8.5.rc1 didn't work perfectly for Nokogiri (see https://github.com/sparklemotion/nokogiri/pull/2974). Specifically: if a system library like `libxml2.so` is installed in a default search path (e.g., this is the case for some system installations of ruby), then the linker dynamically links against the system library rather than statically linking against the packaged static archive.
This PR is an attempt to fix that by asking the developer to pass in the name of the static archive when choosing to statically link. For example:
```ruby
libxml2_recipe.mkmf_config(pkg: "libxml-2.0", static: "xml2")
```
In this case, MiniPortile will now:
- rewrite the linker flags to ensure we link against the packaged static archive
- remove all `-L` and `-l` flags
- inject the full path to the static …

improve mkmf config

---

lib/mini_portile2/mini_portile.rb

This patch fixes the "method redefined" warning that occurs while loading the gem.
```
$ ruby -wrmini_portile2 -ep
.../mini_portile2-2.8.4/lib/mini_portile2/mini_portile.rb:97: warning: method redefined; discarding old source_directory=
```

Eliminate "method redefined" warning

---

lib/mini_portile2/mini_portile_cmake.rb
test/test_cmake.rb

When I built library with the default setting, its compilation has no optimized in my environment.
I want it has release binary by default.
Ref. https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

Create release binary with cmake explicitly

---

.github/workflows/ci.yml

Older rubies are not available on MacOS 14 through setup-ruby; and the libyaml 0.2.5 example does not have up-to-date config.guess/config.sub files to handle arm64-darwin.

ci: pin to macos-13 when necessary

---

README.md
lib/mini_portile2/mini_portile.rb
lib/mini_portile2/mini_portile_cmake.rb
test/helper.rb
test/test_cmake.rb
test/test_cook.rb

Add a `cxx_cmd`. Use it for configuring CMake, removing the logic added in #130 for host-specific binary detection.
Related to #141.

Add `cxx_cmd` which parallels `cc_cmd`

---

.github/workflows/ci.yml
CHANGELOG.md
lib/mini_portile2/mini_portile.rb

* Add OpenBSD to the CI matrix.
* Workaround OpenBSD's `tar` not supporting the `-J` option by using `xzcat $file | tar xf - -C $dest`.

Add OpenBSD support

---

mini_portile2.gemspec

By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/mini_portile which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/

Provide a 'Changelog' link on rubygems.org/gems/mini_portile

---

.github/workflows/downstream.yml

See https://github.com/mudge/re2/issues/158 for discussion about abseil/cmake conflicts.

ci: ignore re2 failures for now

---

.github/workflows/downstream.yml

Reverts flavorjones/mini_portile#148 now that [re2 2.13.2](https://github.com/mudge/re2/releases/tag/v2.13.2) is out which patches Abseil for CMake 3.30.0 support.

Revert "ci: ignore re2 failures for now"

---

lib/mini_portile2/mini_portile.rb

and emit a readable error if it doesn't exist
Thanks to @mattjones for the bug report! ❤️

Check for the existence of xzcat

---

.github/workflows/ci.yml

This started failing suddenly, I imagine because Github's base container removed libiconv or something.
example: https://github.com/flavorjones/mini_portile/actions/runs/12081054688/job/33689444541#step:6:193

ci: brew install libiconv for test-examples on macos

---

Gemfile

Logger has been moved out of the default gems in Ruby 3.5, which was causing failures in the "upstream" CI jobs, e.g. https://github.com/flavorjones/mini_portile/actions/runs/12825003621/job/35762153079#step:5:29
Also group the gems in the Gemfile under the "development" group

dev: add logger to the Gemfile

---

test/assets/test-cmake-1.0/CMakeLists.txt

"Compatibility with CMake < 3.5 has been removed from CMake."

ci: windows images no longer support older cmake versions

---

.github/workflows/ci.yml

openbsd 7.7 doesn't ship with ruby 3.1
trying to fix CI failures e.g. https://github.com/flavorjones/mini_portile/actions/runs/14791258816/job/41561607295

ci: update ruby in the openbsd jobs

---

lib/mini_portile2/mini_portile.rb

Another one (:
In Ruby 3.5 most of the `cgi` gem will be removed. Only the various escape/unescape methods will be retained by default.
On older versions, require `"cgi/util"` is needed because the unescape* methods don't work otherwise. Doing it that way works since Ruby 2.3, which conveniently is the minimum supported ruby version here.
https://bugs.ruby-lang.org/issues/21258

Only load what is required from `cgi`
